// Mocks generated by Mockito 5.0.16 from annotations
// in cardano_wallet_sdk/test/mock_wallet_2.dart.
// Do not manually edit this file.

import 'dart:async' as _i20;
import 'dart:typed_data' as _i28;

import 'package:blockfrost/src/api.dart' as _i19;
import 'package:blockfrost/src/api/cardano_accounts_api.dart' as _i4;
import 'package:blockfrost/src/api/cardano_addresses_api.dart' as _i5;
import 'package:blockfrost/src/api/cardano_assets_api.dart' as _i6;
import 'package:blockfrost/src/api/cardano_blocks_api.dart' as _i7;
import 'package:blockfrost/src/api/cardano_epochs_api.dart' as _i8;
import 'package:blockfrost/src/api/cardano_ledger_api.dart' as _i9;
import 'package:blockfrost/src/api/cardano_metadata_api.dart' as _i10;
import 'package:blockfrost/src/api/cardano_pools_api.dart' as _i11;
import 'package:blockfrost/src/api/cardano_transactions_api.dart' as _i12;
import 'package:blockfrost/src/api/health_api.dart' as _i13;
import 'package:blockfrost/src/api/ipfs_add_api.dart' as _i14;
import 'package:blockfrost/src/api/ipfs_gateway_api.dart' as _i15;
import 'package:blockfrost/src/api/ipfs_pins_api.dart' as _i16;
import 'package:blockfrost/src/api/metrics_api.dart' as _i17;
import 'package:blockfrost/src/api/nut_link_api.dart' as _i18;
import 'package:blockfrost/src/model/account_content.dart' as _i23;
import 'package:blockfrost/src/model/address_content.dart' as _i24;
import 'package:blockfrost/src/model/address_content_total.dart' as _i25;
import 'package:blockfrost/src/model/asset.dart' as _i26;
import 'package:blockfrost/src/model/block_content.dart' as _i27;
import 'package:blockfrost/src/model/tx_content.dart' as _i29;
import 'package:blockfrost/src/model/tx_content_utxo.dart' as _i30;
import 'package:built_collection/built_collection.dart' as _i21;
import 'package:built_value/json_object.dart' as _i22;
import 'package:built_value/serializer.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDio_0 extends _i1.Fake implements _i2.Dio {}

class _FakeSerializers_1 extends _i1.Fake implements _i3.Serializers {}

class _FakeCardanoAccountsApi_2 extends _i1.Fake
    implements _i4.CardanoAccountsApi {}

class _FakeCardanoAddressesApi_3 extends _i1.Fake
    implements _i5.CardanoAddressesApi {}

class _FakeCardanoAssetsApi_4 extends _i1.Fake implements _i6.CardanoAssetsApi {
}

class _FakeCardanoBlocksApi_5 extends _i1.Fake implements _i7.CardanoBlocksApi {
}

class _FakeCardanoEpochsApi_6 extends _i1.Fake implements _i8.CardanoEpochsApi {
}

class _FakeCardanoLedgerApi_7 extends _i1.Fake implements _i9.CardanoLedgerApi {
}

class _FakeCardanoMetadataApi_8 extends _i1.Fake
    implements _i10.CardanoMetadataApi {}

class _FakeCardanoPoolsApi_9 extends _i1.Fake implements _i11.CardanoPoolsApi {}

class _FakeCardanoTransactionsApi_10 extends _i1.Fake
    implements _i12.CardanoTransactionsApi {}

class _FakeHealthApi_11 extends _i1.Fake implements _i13.HealthApi {}

class _FakeIPFSAddApi_12 extends _i1.Fake implements _i14.IPFSAddApi {}

class _FakeIPFSGatewayApi_13 extends _i1.Fake implements _i15.IPFSGatewayApi {}

class _FakeIPFSPinsApi_14 extends _i1.Fake implements _i16.IPFSPinsApi {}

class _FakeMetricsApi_15 extends _i1.Fake implements _i17.MetricsApi {}

class _FakeNutLinkApi_16 extends _i1.Fake implements _i18.NutLinkApi {}

class _FakeBaseOptions_17 extends _i1.Fake implements _i2.BaseOptions {}

class _FakeHttpClientAdapter_18 extends _i1.Fake
    implements _i2.HttpClientAdapter {}

class _FakeTransformer_19 extends _i1.Fake implements _i2.Transformer {}

class _FakeInterceptors_20 extends _i1.Fake implements _i2.Interceptors {}

class _FakeResponse_21<T> extends _i1.Fake implements _i2.Response<T> {}

/// A class which mocks [Blockfrost].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockfrost extends _i1.Mock implements _i19.Blockfrost {
  MockBlockfrost() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_0())
          as _i2.Dio);
  @override
  _i3.Serializers get serializers =>
      (super.noSuchMethod(Invocation.getter(#serializers),
          returnValue: _FakeSerializers_1()) as _i3.Serializers);
  @override
  void setOAuthToken(String? name, String? token) =>
      super.noSuchMethod(Invocation.method(#setOAuthToken, [name, token]),
          returnValueForMissingStub: null);
  @override
  void setBasicAuth(String? name, String? username, String? password) =>
      super.noSuchMethod(
          Invocation.method(#setBasicAuth, [name, username, password]),
          returnValueForMissingStub: null);
  @override
  void setApiKey(String? name, String? apiKey) =>
      super.noSuchMethod(Invocation.method(#setApiKey, [name, apiKey]),
          returnValueForMissingStub: null);
  @override
  _i4.CardanoAccountsApi getCardanoAccountsApi() =>
      (super.noSuchMethod(Invocation.method(#getCardanoAccountsApi, []),
          returnValue: _FakeCardanoAccountsApi_2()) as _i4.CardanoAccountsApi);
  @override
  _i5.CardanoAddressesApi getCardanoAddressesApi() => (super.noSuchMethod(
      Invocation.method(#getCardanoAddressesApi, []),
      returnValue: _FakeCardanoAddressesApi_3()) as _i5.CardanoAddressesApi);
  @override
  _i6.CardanoAssetsApi getCardanoAssetsApi() =>
      (super.noSuchMethod(Invocation.method(#getCardanoAssetsApi, []),
          returnValue: _FakeCardanoAssetsApi_4()) as _i6.CardanoAssetsApi);
  @override
  _i7.CardanoBlocksApi getCardanoBlocksApi() =>
      (super.noSuchMethod(Invocation.method(#getCardanoBlocksApi, []),
          returnValue: _FakeCardanoBlocksApi_5()) as _i7.CardanoBlocksApi);
  @override
  _i8.CardanoEpochsApi getCardanoEpochsApi() =>
      (super.noSuchMethod(Invocation.method(#getCardanoEpochsApi, []),
          returnValue: _FakeCardanoEpochsApi_6()) as _i8.CardanoEpochsApi);
  @override
  _i9.CardanoLedgerApi getCardanoLedgerApi() =>
      (super.noSuchMethod(Invocation.method(#getCardanoLedgerApi, []),
          returnValue: _FakeCardanoLedgerApi_7()) as _i9.CardanoLedgerApi);
  @override
  _i10.CardanoMetadataApi getCardanoMetadataApi() =>
      (super.noSuchMethod(Invocation.method(#getCardanoMetadataApi, []),
          returnValue: _FakeCardanoMetadataApi_8()) as _i10.CardanoMetadataApi);
  @override
  _i11.CardanoPoolsApi getCardanoPoolsApi() =>
      (super.noSuchMethod(Invocation.method(#getCardanoPoolsApi, []),
          returnValue: _FakeCardanoPoolsApi_9()) as _i11.CardanoPoolsApi);
  @override
  _i12.CardanoTransactionsApi getCardanoTransactionsApi() =>
      (super.noSuchMethod(Invocation.method(#getCardanoTransactionsApi, []),
              returnValue: _FakeCardanoTransactionsApi_10())
          as _i12.CardanoTransactionsApi);
  @override
  _i13.HealthApi getHealthApi() =>
      (super.noSuchMethod(Invocation.method(#getHealthApi, []),
          returnValue: _FakeHealthApi_11()) as _i13.HealthApi);
  @override
  _i14.IPFSAddApi getIPFSAddApi() =>
      (super.noSuchMethod(Invocation.method(#getIPFSAddApi, []),
          returnValue: _FakeIPFSAddApi_12()) as _i14.IPFSAddApi);
  @override
  _i15.IPFSGatewayApi getIPFSGatewayApi() =>
      (super.noSuchMethod(Invocation.method(#getIPFSGatewayApi, []),
          returnValue: _FakeIPFSGatewayApi_13()) as _i15.IPFSGatewayApi);
  @override
  _i16.IPFSPinsApi getIPFSPinsApi() =>
      (super.noSuchMethod(Invocation.method(#getIPFSPinsApi, []),
          returnValue: _FakeIPFSPinsApi_14()) as _i16.IPFSPinsApi);
  @override
  _i17.MetricsApi getMetricsApi() =>
      (super.noSuchMethod(Invocation.method(#getMetricsApi, []),
          returnValue: _FakeMetricsApi_15()) as _i17.MetricsApi);
  @override
  _i18.NutLinkApi getNutLinkApi() =>
      (super.noSuchMethod(Invocation.method(#getNutLinkApi, []),
          returnValue: _FakeNutLinkApi_16()) as _i18.NutLinkApi);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i2.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options =>
      (super.noSuchMethod(Invocation.getter(#options),
          returnValue: _FakeBaseOptions_17()) as _i2.BaseOptions);
  @override
  set options(_i2.BaseOptions? _options) =>
      super.noSuchMethod(Invocation.setter(#options, _options),
          returnValueForMissingStub: null);
  @override
  _i2.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(Invocation.getter(#httpClientAdapter),
          returnValue: _FakeHttpClientAdapter_18()) as _i2.HttpClientAdapter);
  @override
  set httpClientAdapter(_i2.HttpClientAdapter? _httpClientAdapter) => super
      .noSuchMethod(Invocation.setter(#httpClientAdapter, _httpClientAdapter),
          returnValueForMissingStub: null);
  @override
  _i2.Transformer get transformer =>
      (super.noSuchMethod(Invocation.getter(#transformer),
          returnValue: _FakeTransformer_19()) as _i2.Transformer);
  @override
  set transformer(_i2.Transformer? _transformer) =>
      super.noSuchMethod(Invocation.setter(#transformer, _transformer),
          returnValueForMissingStub: null);
  @override
  _i2.Interceptors get interceptors =>
      (super.noSuchMethod(Invocation.getter(#interceptors),
          returnValue: _FakeInterceptors_20()) as _i2.Interceptors);
  @override
  void close({bool? force = false}) =>
      super.noSuchMethod(Invocation.method(#close, [], {#force: force}),
          returnValueForMissingStub: null);
  @override
  _i20.Future<_i2.Response<T>> get<T>(String? path,
          {Map<String, dynamic>? queryParameters,
          _i2.Options? options,
          _i2.CancelToken? cancelToken,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#get, [
                path
              ], {
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> getUri<T>(Uri? uri,
          {_i2.Options? options,
          _i2.CancelToken? cancelToken,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#getUri, [
                uri
              ], {
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> post<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i2.Options? options,
          _i2.CancelToken? cancelToken,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> postUri<T>(Uri? uri,
          {dynamic data,
          _i2.Options? options,
          _i2.CancelToken? cancelToken,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#postUri, [
                uri
              ], {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> put<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i2.Options? options,
          _i2.CancelToken? cancelToken,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> putUri<T>(Uri? uri,
          {dynamic data,
          _i2.Options? options,
          _i2.CancelToken? cancelToken,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#putUri, [
                uri
              ], {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> head<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i2.Options? options,
          _i2.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#head, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> headUri<T>(Uri? uri,
          {dynamic data, _i2.Options? options, _i2.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#headUri, [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken}),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> delete<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i2.Options? options,
          _i2.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> deleteUri<T>(Uri? uri,
          {dynamic data, _i2.Options? options, _i2.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteUri, [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken}),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> patch<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i2.Options? options,
          _i2.CancelToken? cancelToken,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> patchUri<T>(Uri? uri,
          {dynamic data,
          _i2.Options? options,
          _i2.CancelToken? cancelToken,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#patchUri, [
                uri
              ], {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  void lock() => super.noSuchMethod(Invocation.method(#lock, []),
      returnValueForMissingStub: null);
  @override
  void unlock() => super.noSuchMethod(Invocation.method(#unlock, []),
      returnValueForMissingStub: null);
  @override
  void clear() => super.noSuchMethod(Invocation.method(#clear, []),
      returnValueForMissingStub: null);
  @override
  _i20.Future<_i2.Response<dynamic>> download(String? urlPath, dynamic savePath,
          {_i2.ProgressCallback? onReceiveProgress,
          Map<String, dynamic>? queryParameters,
          _i2.CancelToken? cancelToken,
          bool? deleteOnError = true,
          String? lengthHeader = r'content-length',
          dynamic data,
          _i2.Options? options}) =>
      (super.noSuchMethod(
              Invocation.method(#download, [
                urlPath,
                savePath
              ], {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options
              }),
              returnValue: Future<_i2.Response<dynamic>>.value(
                  _FakeResponse_21<dynamic>()))
          as _i20.Future<_i2.Response<dynamic>>);
  @override
  _i20.Future<_i2.Response<dynamic>> downloadUri(Uri? uri, dynamic savePath,
          {_i2.ProgressCallback? onReceiveProgress,
          _i2.CancelToken? cancelToken,
          bool? deleteOnError = true,
          String? lengthHeader = r'content-length',
          dynamic data,
          _i2.Options? options}) =>
      (super.noSuchMethod(
              Invocation.method(#downloadUri, [
                uri,
                savePath
              ], {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options
              }),
              returnValue: Future<_i2.Response<dynamic>>.value(
                  _FakeResponse_21<dynamic>()))
          as _i20.Future<_i2.Response<dynamic>>);
  @override
  _i20.Future<_i2.Response<T>> request<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i2.CancelToken? cancelToken,
          _i2.Options? options,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#request, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> requestUri<T>(Uri? uri,
          {dynamic data,
          _i2.CancelToken? cancelToken,
          _i2.Options? options,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#requestUri, [
                uri
              ], {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  _i20.Future<_i2.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(Invocation.method(#fetch, [requestOptions]),
              returnValue: Future<_i2.Response<T>>.value(_FakeResponse_21<T>()))
          as _i20.Future<_i2.Response<T>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CardanoAccountsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardanoAccountsApi extends _i1.Mock
    implements _i4.CardanoAccountsApi {
  MockCardanoAccountsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>
      accountsStakeAddressAddressesAssetsGet(
              {String? stakeAddress,
              int? count,
              int? page,
              String? order,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
              Invocation.method(#accountsStakeAddressAddressesAssetsGet, [], {
                #stakeAddress: stakeAddress,
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<
                      _i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                  _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>())) as _i20
              .Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>
      accountsStakeAddressAddressesGet(
              {String? stakeAddress,
              int? count,
              int? page,
              String? order,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
                  Invocation.method(#accountsStakeAddressAddressesGet, [], {
                    #stakeAddress: stakeAddress,
                    #count: count,
                    #page: page,
                    #order: order,
                    #cancelToken: cancelToken,
                    #headers: headers,
                    #extra: extra,
                    #validateStatus: validateStatus,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress
                  }),
                  returnValue: Future<
                          _i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
              as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>
      accountsStakeAddressDelegationsGet(
              {String? stakeAddress,
              int? count,
              int? page,
              String? order,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
                  Invocation.method(#accountsStakeAddressDelegationsGet, [], {
                    #stakeAddress: stakeAddress,
                    #count: count,
                    #page: page,
                    #order: order,
                    #cancelToken: cancelToken,
                    #headers: headers,
                    #extra: extra,
                    #validateStatus: validateStatus,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress
                  }),
                  returnValue: Future<
                          _i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
              as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i23.AccountContent>> accountsStakeAddressGet(
          {String? stakeAddress,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#accountsStakeAddressGet, [], {
                #stakeAddress: stakeAddress,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i23.AccountContent>>.value(
                  _FakeResponse_21<_i23.AccountContent>()))
          as _i20.Future<_i2.Response<_i23.AccountContent>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>
      accountsStakeAddressHistoryGet(
              {String? stakeAddress,
              int? count,
              int? page,
              String? order,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
                  Invocation.method(#accountsStakeAddressHistoryGet, [], {
                    #stakeAddress: stakeAddress,
                    #count: count,
                    #page: page,
                    #order: order,
                    #cancelToken: cancelToken,
                    #headers: headers,
                    #extra: extra,
                    #validateStatus: validateStatus,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress
                  }),
                  returnValue: Future<
                          _i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
              as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>
      accountsStakeAddressMirsGet(
              {String? stakeAddress,
              int? count,
              int? page,
              String? order,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
                  Invocation.method(#accountsStakeAddressMirsGet, [], {
                    #stakeAddress: stakeAddress,
                    #count: count,
                    #page: page,
                    #order: order,
                    #cancelToken: cancelToken,
                    #headers: headers,
                    #extra: extra,
                    #validateStatus: validateStatus,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress
                  }),
                  returnValue: Future<
                          _i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
              as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>
      accountsStakeAddressRegistrationsGet(
              {String? stakeAddress,
              int? count,
              int? page,
              String? order,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
                  Invocation.method(#accountsStakeAddressRegistrationsGet, [], {
                    #stakeAddress: stakeAddress,
                    #count: count,
                    #page: page,
                    #order: order,
                    #cancelToken: cancelToken,
                    #headers: headers,
                    #extra: extra,
                    #validateStatus: validateStatus,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress
                  }),
                  returnValue: Future<
                          _i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
              as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>
      accountsStakeAddressRewardsGet(
              {String? stakeAddress,
              int? count,
              int? page,
              String? order,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
                  Invocation.method(#accountsStakeAddressRewardsGet, [], {
                    #stakeAddress: stakeAddress,
                    #count: count,
                    #page: page,
                    #order: order,
                    #cancelToken: cancelToken,
                    #headers: headers,
                    #extra: extra,
                    #validateStatus: validateStatus,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress
                  }),
                  returnValue: Future<
                          _i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
              as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>
      accountsStakeAddressWithdrawalsGet(
              {String? stakeAddress,
              int? count,
              int? page,
              String? order,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
                  Invocation.method(#accountsStakeAddressWithdrawalsGet, [], {
                    #stakeAddress: stakeAddress,
                    #count: count,
                    #page: page,
                    #order: order,
                    #cancelToken: cancelToken,
                    #headers: headers,
                    #extra: extra,
                    #validateStatus: validateStatus,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress
                  }),
                  returnValue: Future<
                          _i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
              as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CardanoAddressesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardanoAddressesApi extends _i1.Mock
    implements _i5.CardanoAddressesApi {
  MockCardanoAddressesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i2.Response<_i24.AddressContent>> addressesAddressGet(
          {String? address,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#addressesAddressGet, [], {
                #address: address,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i24.AddressContent>>.value(
                  _FakeResponse_21<_i24.AddressContent>()))
          as _i20.Future<_i2.Response<_i24.AddressContent>>);
  @override
  _i20.Future<_i2.Response<_i25.AddressContentTotal>> addressesAddressTotalGet(
          {String? address,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#addressesAddressTotalGet, [], {
                #address: address,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i25.AddressContentTotal>>.value(
                  _FakeResponse_21<_i25.AddressContentTotal>()))
          as _i20.Future<_i2.Response<_i25.AddressContentTotal>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>
      addressesAddressTransactionsGet(
              {String? address,
              int? count,
              int? page,
              String? order,
              String? from,
              String? to,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
                  Invocation.method(#addressesAddressTransactionsGet, [], {
                    #address: address,
                    #count: count,
                    #page: page,
                    #order: order,
                    #from: from,
                    #to: to,
                    #cancelToken: cancelToken,
                    #headers: headers,
                    #extra: extra,
                    #validateStatus: validateStatus,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress
                  }),
                  returnValue: Future<
                          _i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
              as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<String>>> addressesAddressTxsGet(
          {String? address,
          int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#addressesAddressTxsGet, [], {
                #address: address,
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i21.BuiltList<String>>>.value(
                  _FakeResponse_21<_i21.BuiltList<String>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<String>>>);
  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> addressesAddressUtxosGet(
          {String? address,
          int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#addressesAddressUtxosGet, [], {
                #address: address,
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CardanoAssetsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardanoAssetsApi extends _i1.Mock implements _i6.CardanoAssetsApi {
  MockCardanoAssetsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> assetsAssetAddressesGet(
          {String? asset,
          int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#assetsAssetAddressesGet, [], {
                #asset: asset,
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i26.Asset>> assetsAssetGet(
          {String? asset,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#assetsAssetGet, [], {
                #asset: asset,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i26.Asset>>.value(
                  _FakeResponse_21<_i26.Asset>()))
          as _i20.Future<_i2.Response<_i26.Asset>>);
  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> assetsAssetHistoryGet(
          {String? asset,
          int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#assetsAssetHistoryGet, [], {
                #asset: asset,
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> assetsAssetTransactionsGet(
          {String? asset,
          int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#assetsAssetTransactionsGet, [], {
                #asset: asset,
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<String>>> assetsAssetTxsGet(
          {String? asset,
          int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#assetsAssetTxsGet, [], {
                #asset: asset,
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i21.BuiltList<String>>>.value(
                  _FakeResponse_21<_i21.BuiltList<String>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<String>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>> assetsGet(
          {int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#assetsGet, [], {
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> assetsPolicyPolicyIdGet(
          {String? policyId,
          int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#assetsPolicyPolicyIdGet, [], {
                #policyId: policyId,
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CardanoBlocksApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardanoBlocksApi extends _i1.Mock implements _i7.CardanoBlocksApi {
  MockCardanoBlocksApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i2.Response<_i27.BlockContent>>
      blocksEpochEpochNumberSlotSlotNumberGet(
              {int? epochNumber,
              int? slotNumber,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
              Invocation.method(#blocksEpochEpochNumberSlotSlotNumberGet, [], {
                #epochNumber: epochNumber,
                #slotNumber: slotNumber,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i27.BlockContent>>.value(
                  _FakeResponse_21<_i27.BlockContent>())) as _i20
              .Future<_i2.Response<_i27.BlockContent>>);
  @override
  _i20.Future<_i2.Response<_i27.BlockContent>> blocksHashOrNumberGet(
          {String? hashOrNumber,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#blocksHashOrNumberGet, [], {
                #hashOrNumber: hashOrNumber,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i27.BlockContent>>.value(
                  _FakeResponse_21<_i27.BlockContent>()))
          as _i20.Future<_i2.Response<_i27.BlockContent>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i27.BlockContent>>>
      blocksHashOrNumberNextGet(
              {String? hashOrNumber,
              int? count,
              int? page,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
              Invocation.method(#blocksHashOrNumberNextGet, [], {
                #hashOrNumber: hashOrNumber,
                #count: count,
                #page: page,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i27.BlockContent>>>.value(
                      _FakeResponse_21<
                          _i21.BuiltList<_i27.BlockContent>>())) as _i20
              .Future<_i2.Response<_i21.BuiltList<_i27.BlockContent>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i27.BlockContent>>>
      blocksHashOrNumberPreviousGet(
              {String? hashOrNumber,
              int? count,
              int? page,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
              Invocation.method(#blocksHashOrNumberPreviousGet, [], {
                #hashOrNumber: hashOrNumber,
                #count: count,
                #page: page,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i27.BlockContent>>>.value(
                      _FakeResponse_21<
                          _i21.BuiltList<_i27.BlockContent>>())) as _i20
              .Future<_i2.Response<_i21.BuiltList<_i27.BlockContent>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<String>>> blocksHashOrNumberTxsGet(
          {String? hashOrNumber,
          int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#blocksHashOrNumberTxsGet, [], {
                #hashOrNumber: hashOrNumber,
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i21.BuiltList<String>>>.value(
                  _FakeResponse_21<_i21.BuiltList<String>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<String>>>);
  @override
  _i20.Future<_i2.Response<_i27.BlockContent>> blocksLatestGet(
          {_i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#blocksLatestGet, [], {
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i27.BlockContent>>.value(
                  _FakeResponse_21<_i27.BlockContent>()))
          as _i20.Future<_i2.Response<_i27.BlockContent>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<String>>> blocksLatestTxsGet(
          {int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#blocksLatestTxsGet, [], {
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i21.BuiltList<String>>>.value(
                  _FakeResponse_21<_i21.BuiltList<String>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<String>>>);
  @override
  _i20.Future<_i2.Response<_i27.BlockContent>> blocksSlotSlotNumberGet(
          {int? slotNumber,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#blocksSlotSlotNumberGet, [], {
                #slotNumber: slotNumber,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i27.BlockContent>>.value(
                  _FakeResponse_21<_i27.BlockContent>()))
          as _i20.Future<_i2.Response<_i27.BlockContent>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CardanoMetadataApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardanoMetadataApi extends _i1.Mock
    implements _i10.CardanoMetadataApi {
  MockCardanoMetadataApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> metadataTxsLabelsGet(
          {int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#metadataTxsLabelsGet, [], {
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>
      metadataTxsLabelsLabelCborGet(
              {String? label,
              int? count,
              int? page,
              String? order,
              _i2.CancelToken? cancelToken,
              Map<String, dynamic>? headers,
              Map<String, dynamic>? extra,
              _i2.ValidateStatus? validateStatus,
              _i2.ProgressCallback? onSendProgress,
              _i2.ProgressCallback? onReceiveProgress}) =>
          (super.noSuchMethod(
                  Invocation.method(#metadataTxsLabelsLabelCborGet, [], {
                    #label: label,
                    #count: count,
                    #page: page,
                    #order: order,
                    #cancelToken: cancelToken,
                    #headers: headers,
                    #extra: extra,
                    #validateStatus: validateStatus,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress
                  }),
                  returnValue: Future<
                          _i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
              as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> metadataTxsLabelsLabelGet(
          {String? label,
          int? count,
          int? page,
          String? order,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#metadataTxsLabelsLabelGet, [], {
                #label: label,
                #count: count,
                #page: page,
                #order: order,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CardanoTransactionsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardanoTransactionsApi extends _i1.Mock
    implements _i12.CardanoTransactionsApi {
  MockCardanoTransactionsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i2.Response<String>> txSubmitPost(
          {String? contentType,
          _i28.Uint8List? data,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txSubmitPost, [], {
                #contentType: contentType,
                #data: data,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<String>>.value(
                  _FakeResponse_21<String>()))
          as _i20.Future<_i2.Response<String>>);
  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> txsHashDelegationsGet(
          {String? hash,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txsHashDelegationsGet, [], {
                #hash: hash,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i29.TxContent>> txsHashGet(
          {String? hash,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txsHashGet, [], {
                #hash: hash,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i29.TxContent>>.value(
                  _FakeResponse_21<_i29.TxContent>()))
          as _i20.Future<_i2.Response<_i29.TxContent>>);
  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> txsHashMetadataCborGet(
          {String? hash,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txsHashMetadataCborGet, [], {
                #hash: hash,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>> txsHashMetadataGet(
          {String? hash,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txsHashMetadataGet, [], {
                #hash: hash,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>> txsHashMirsGet(
          {String? hash,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txsHashMirsGet, [], {
                #hash: hash,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> txsHashPoolRetiresGet(
          {String? hash,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txsHashPoolRetiresGet, [], {
                #hash: hash,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> txsHashPoolUpdatesGet(
          {String? hash,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txsHashPoolUpdatesGet, [], {
                #hash: hash,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>> txsHashStakesGet(
          {String? hash,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txsHashStakesGet, [], {
                #hash: hash,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  _i20.Future<_i2.Response<_i30.TxContentUtxo>> txsHashUtxosGet(
          {String? hash,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txsHashUtxosGet, [], {
                #hash: hash,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i2.Response<_i30.TxContentUtxo>>.value(
                  _FakeResponse_21<_i30.TxContentUtxo>()))
          as _i20.Future<_i2.Response<_i30.TxContentUtxo>>);
  @override
  _i20.Future<
      _i2.Response<_i21.BuiltList<_i22.JsonObject>>> txsHashWithdrawalsGet(
          {String? hash,
          _i2.CancelToken? cancelToken,
          Map<String, dynamic>? headers,
          Map<String, dynamic>? extra,
          _i2.ValidateStatus? validateStatus,
          _i2.ProgressCallback? onSendProgress,
          _i2.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#txsHashWithdrawalsGet, [], {
                #hash: hash,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue:
                  Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>.value(
                      _FakeResponse_21<_i21.BuiltList<_i22.JsonObject>>()))
          as _i20.Future<_i2.Response<_i21.BuiltList<_i22.JsonObject>>>);
  @override
  String toString() => super.toString();
}
